name: Build Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    env:
      SolutionPath: 'Source\PersonalCloudSetup.sln'
      Configuration: 'Release'

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }} 
          submodules: 'recursive'

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.202

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.0

      - name: Setup Wix Toolset
        run: |
            Invoke-WebRequest https://www.nuget.org/api/v2/package/WixSharp.wix.bin/3.11.2 -Out .\WixSharp.wix.bin.zip
            Expand-Archive -Path .\WixSharp.wix.bin.zip -DestinationPath .\WixSharp.wix.bin
            mkdir .\Data\wix_bin
            Move-Item -Path .\WixSharp.wix.bin\tools\ -Filter *.* -Destination .\Data\wix_bin\tools\
            .\Data\UpdateManifest.exe .\Data\wix_bin\tools\bin\x86\burn.exe
            del .\Data\UpdateManifest.exe

      - name: Download ffmpeg
        run: |
            Invoke-WebRequest https://ffmpeg.zeranoe.com/builds/win32/static/ffmpeg-4.2.3-win32-static.zip -Out .\ffmpeg-4.2.3-win32-static.zip
            Invoke-WebRequest https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-4.2.3-win64-static.zip -Out .\ffmpeg-4.2.3-win64-static.zip

      - name: Extract ffmpeg
        run: |
            Expand-Archive -Path .\ffmpeg-4.2.3-win32-static.zip -DestinationPath .\
            Copy-Item -Path .\ffmpeg-4.2.3-win32-static\bin\ -Filter ffmpeg.exe -Destination .\Data\ffmpeg_bin\x86\ -Recurse
            Expand-Archive -Path .\ffmpeg-4.2.3-win64-static.zip -DestinationPath .\
            Copy-Item -Path .\ffmpeg-4.2.3-win64-static\bin\ -Filter ffmpeg.exe -Destination .\Data\ffmpeg_bin\x64\ -Recurse

      - name: Restore
        run: msbuild $env:SolutionPath /t:Restore /p:Configuration=$env:Configuration

      - name: Build
        run: msbuild $env:SolutionPath /v:d /t:Rebuild /p:Configuration=$env:Configuration /maxCpuCount

      - name: Create Zip File
        run: Compress-Archive -Path ".\Source\PersonalCloudSetup\bin\Release\*",".\Data" -DestinationPath .\PersonalCloudSetup.zip
          
      - name: Upload Zip File
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./PersonalCloudSetup.zip
          asset_name: PersonalCloudSetup.zip
          asset_content_type: application/zip
